### PR TITLE
Fix food-world-cup README

### PR DESCRIPTION
**Pull request by jblang94**
This PR fixes an "Anwser" typo and clarifies food-world-cup README

### CODE REVIEW

**Comment by jblang94** [comment]
@dmil when you have time, could you please have a look at my changes? thank you

**Comment by Assamdiapak** [comment]
scripts": {
    "lint": "jshint . && jscs lib test",
    "test": "npm run lint && mocha --color",
    "coverage": "unit-coverage run -p common",
    "coverage-html": "unit-coverage run -p common -r html -o coverage.html",
    "changelog": "git log `git describe --tags --abbrev=0`..HEAD --pretty=format:' * %s (%an)' | grep -v 'Merge pull request'",
    "release": "npm test && npm publish",
    "travis": "npm run test && unit-coverage run -p common -r lcov -o out.lcov && cat out.lcov | coveralls"
  },
  "files": [
    "lib",
    "LICENSE"
  ]
}

**Comment by shuvsahmed** [comment]
Hi.

**Comment by edujobscircular** [comment]
I can't understand how to work this site. Please get some new of [fifa](http://wincups.com/fifa/)

**Pull request closed without merging**
