### PR TITLE
Update processData.SQL subreddit ambiguity

### PR DESCRIPTION
**Pull request by karolismatul**
A fix for Bigquery Error: 2.40 - 2.68: Ambiguous column name subreddit.

### CODE REVIEW

**Comment by panyarerk** [comment]
Chack balance account of my (TOKEN)

**Comment by jagnarong** [comment]
Good

**Comment by adiebohi** [comment]
Update processData.SQL subreddit ambiguity
Update processData.sql

**Comment by tps288** [comment]
hi

**Comment by vicdes77** [comment]
I'm not doing any of this to my phone, I need and wNt it to stop

**Comment by drvegass** [comment]
Yop

**Pull request merged**
