### PR TITLE
Updated links to use https

### PR DESCRIPTION
**Pull request by mbrickn**
Updated links to use https to avoid a redirect.

### CODE REVIEW

**Comment by noylove** [comment]
https://projects.fivethirtyeight.com/soccer-api/club/spi_global_rankings.csv

**Comment by currencyInvestments** [comment]
Good

**Comment by ascheink** [comment]
Looks good. Thanks @mbrickn.

**Comment by yamaste** [comment]
wishful thinking

**Comment by yamaste** [comment]
so i really have my work cut out for me then

**Comment by kannika220839** [comment]
poppykannika

**Pull request merged**
