### PR TITLE
Changes encoding to UTF-8 to fix load error.

### PR DESCRIPTION
**Pull request by mikeckennedy**
Hi folks. There is some kind of error in this CSV document that breaks apps trying to load it as a basic UTF-8 text file. See the image below. This PR loads, converts, then saves to UTF-8 this content.

### CODE REVIEW

**Comment by mikeckennedy** [comment]
Here's the screenshot for the error.

screen shot 2018-04-30 at 2 19 11 pm

**Comment by nokrock** [comment]
หนังโป๊

**Comment by RENYS** [comment]
Take me out of that..i dont want recevie nothing because not my thing..i have no interess ok..please..

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by mikeckennedy** [comment]
Hi guys. Are you planning on accepting this PR? Just want to let some users of the data know one way or the other.

**Comment by wartime7** [comment]
What is this

xxx

On Jun 17, 2018 11:25 PM, "Cassi Shipman" <notifications@github.com> wrote:

Fuck me please
[image: received_141139853377046]
<https://user-images.githubusercontent.com/39807526/41518062-9518cd84-7285-11e8-9f07-0ce5d1523edb.jpeg>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/fivethirtyeight/data/pull/181#issuecomment-397938723>,
or mute the thread

**Comment by wartime7** [comment]
Huh

**Pull request merged**
